# ==============================================================================
# Humanoid Learning - Policy Export
# ==============================================================================

load("@rl_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "export_lib",
    srcs = [
        "__init__.py",
        "export_onnx.py",
    ],
    deps = [
        "//humanoid_learning/training:training_lib",
        requirement("jax"),
        requirement("jaxlib"),
        requirement("numpy"),
        requirement("onnx"),
    ],
)

py_binary(
    name = "export_onnx",
    srcs = ["export_onnx.py"],
    deps = [
        ":export_lib",
    ],
)
