/******************************************************************************
Copyright (c) 2017, Farbod Farshidian. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************************/

/*
 * The steppers below are ports of the odeint steppers OCS2 used before (euler, modified_midpoint, runge_kutta4,
 * runge_kutta_dopri5 and controlled_runge_kutta with odeint's default error checker and step adjuster, as instantiated
 * with vector_space_algebra on Eigen vectors). Every arithmetic expression is kept in the form odeint evaluated it, so
 * the results are bit-identical to odeint's on the same compiler and flags.
 *
 * odeint: Copyright 2010-2013 Karsten Ahnert, Copyright 2010-2013 Mario Mulansky. Distributed under the Boost Software
 * License, Version 1.0:
 *
 *   Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 *   accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 *   and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 *   Software is furnished to do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including the above license grant, this
 *   restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative works are solely in the form of
 *   machine-executable object code generated by a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *   WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 *   COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 *   CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

#pragma once

#include <ocs2_core/Types.h>
#include <ocs2_core/integration/IntegratorBase.h>

namespace ocs2 {
namespace steppers {

using system_func_t = IntegratorBase::system_func_t;

/** The outcome of one attempt of a controlled stepper (odeint's controlled_step_result). */
enum class StepResult { kSuccess, kFail };

/**
 * Explicit Euler (odeint's euler): x <- x + dt * f(x, t). One evaluation of the system per step.
 */
class Euler {
 public:
  /** Advances `x` from `t` by `dt`. */
  void doStep(const system_func_t& system, vector_t& x, scalar_t t, scalar_t dt);

 private:
  vector_t dxdt_;
};

/**
 * The modified midpoint method (odeint's modified_midpoint) with its default of two sub-steps: three evaluations of
 * the system per step.
 */
class ModifiedMidpoint {
 public:
  /** Advances `x` from `t` by `dt`. */
  void doStep(const system_func_t& system, vector_t& x, scalar_t t, scalar_t dt);

 private:
  static constexpr unsigned short kSteps = 2;

  vector_t dxdt_;
  vector_t x0_;
  vector_t x1_;
  vector_t dxdtMidpoint_;
};

/**
 * The classical fourth-order Runge-Kutta method (odeint's runge_kutta4, an explicit_generic_rk): four evaluations of
 * the system per step.
 */
class RungeKutta4 {
 public:
  /** Advances `x` from `t` by `dt`. */
  void doStep(const system_func_t& system, vector_t& x, scalar_t t, scalar_t dt);

 private:
  vector_t dxdt_;
  vector_t xTmp_;
  vector_t f0_;
  vector_t f1_;
  vector_t f2_;
};

/**
 * The Dormand-Prince 5(4) pair (odeint's runge_kutta_dopri5). It is first-same-as-last: the derivative at the end of a
 * step is the one the next step starts from, so a step costs six evaluations of the system and the first step one more.
 */
class DormandPrince5 {
 public:
  static constexpr unsigned short kStepperOrder = 5;
  static constexpr unsigned short kErrorOrder = 4;

  /**
   * Advances `x` from `t` by `dt` without error control (odeint's do_step(system, x, t, dt)). The first call evaluates
   * the derivative at (x, t); later calls reuse the derivative the previous step ended with.
   */
  void doStep(const system_func_t& system, vector_t& x, scalar_t t, scalar_t dt);

  /**
   * One step from (`in`, `dxdtIn`, `t`) to (`out`, `dxdtOut`, `t + dt`). `out` may be `in` and `dxdtOut` may be
   * `dxdtIn`.
   */
  void step(
      const system_func_t& system, const vector_t& in, const vector_t& dxdtIn, scalar_t t, vector_t& out, vector_t& dxdtOut, scalar_t dt);

  /**
   * As step(), and writes the estimate of the local error of the step to `xErr`. `out` and `dxdtOut` must be distinct
   * from `in` and `dxdtIn`.
   */
  void stepWithError(const system_func_t& system,
                     const vector_t& in,
                     const vector_t& dxdtIn,
                     scalar_t t,
                     vector_t& out,
                     vector_t& dxdtOut,
                     scalar_t dt,
                     vector_t& xErr);

 private:
  bool initialized_ = false;
  vector_t dxdt_;
  vector_t xTmp_;
  vector_t k2_;
  vector_t k3_;
  vector_t k4_;
  vector_t k5_;
  vector_t k6_;
};

/**
 * Step-size control around DormandPrince5 (odeint's controlled_runge_kutta<runge_kutta_dopri5>, as make_controlled
 * builds it, with the default error checker and step adjuster and no maximal step size).
 *
 * The error of a step is max_i |err_i| / (absTol + relTol * (|x_i| + |dt| * |dxdt_i|)). Above 1 the step is rejected and
 * dt shrinks by max(0.9 * error^(-1/3), 0.2); otherwise it is accepted, and below 0.5 dt grows by
 * 0.9 * max(error, 5^-5)^(-1/5).
 */
class ControlledDormandPrince5 {
 public:
  ControlledDormandPrince5(scalar_t absTol, scalar_t relTol) : absTol_(absTol), relTol_(relTol) {}

  /**
   * Attempts one step of size `dt` from (`x`, `t`). On success `x` and `t` advance and `dt` is the proposal for the next
   * step; on failure only `dt` changes, to the size to retry with.
   */
  StepResult tryStep(const system_func_t& system, vector_t& x, scalar_t& t, scalar_t& dt);

 private:
  /** The normalized error of a step, overwriting `xErr` with the per-coordinate ratios. */
  scalar_t error(const vector_t& xOld, const vector_t& dxdtOld, vector_t& xErr, scalar_t dt) const;

  static scalar_t decreaseStep(scalar_t dt, scalar_t error, int errorOrder);
  static scalar_t increaseStep(scalar_t dt, scalar_t error, int stepperOrder);

  scalar_t absTol_;
  scalar_t relTol_;
  DormandPrince5 stepper_;
  bool initialized_ = false;
  vector_t dxdt_;
  vector_t xErr_;
  vector_t xNew_;
  vector_t dxdtNew_;
};

}  // namespace steppers
}  // namespace ocs2
