# Copyright (c) 2026, Nicholas Palomo. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""Every first-party C++ and Python file starts with the repository's BSD-3 license block (AGENTS.md; decision D5).

The block is the file's first comment: one or more holder lines, `Copyright (c) <year>[-<year>], <holder>. All rights
reserved.`, then the preamble, the three conditions of the BSD 3-Clause License and its disclaimer, in the language's
comment syntax (a `/* ... */` block or `//` lines in C++, `#` lines in Python, below a shebang). The text is compared
with the comment markers, bullets and line breaks taken out, so a block may be wrapped as the file's comment style
wraps it. A new file's holder line is `Copyright (c) <year>, Nicholas Palomo. All rights reserved.`; an existing holder
line is kept.

- `license-header`: a C++ file whose block is missing, has a holder line without its holder, or lacks a part of the
  license. A file whose first comment starts with "Generated by" (the nproto generator's output) is exempt.
- `py-license-header` (tools/hooks/python_docstrings.py) reports the same problems in a Python file, with problems().

cpplint's `legal/copyright` only looks for the word "Copyright"; these checks read the whole block.
"""

import re

from tools.hooks import check_types
from tools.hooks import cpp_source
from tools.hooks import lint_files

NAME = "license-header"

# The text of LICENSE_FILE (test_license_header.py compares them).
HOLDER_LINE = re.compile(
    r"^Copyright \(c\) \d{4}(?:-\d{4})?, [^\s.,][^.]*\. All rights reserved\.$"
)
PREAMBLE = (
    "Redistribution and use in source and binary forms, with or without modification, are permitted provided that "
    "the following conditions are met:"
)
CONDITIONS = (
    (
        "the source-code condition",
        "Redistributions of source code must retain the above copyright notice, this list of conditions and the "
        "following disclaimer.",
    ),
    (
        "the binary-form condition",
        "Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the "
        "following disclaimer in the documentation and/or other materials provided with the distribution.",
    ),
    (
        "the endorsement condition",
        "Neither the name of the copyright holder nor the names of its contributors may be used to endorse or "
        "promote products derived from this software without specific prior written permission.",
    ),
)
DISCLAIMER = (
    'THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED '
    "WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR "
    "PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, "
    "INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT "
    "OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON "
    "ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) "
    "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
)

# The repository's license, whose text every block repeats.
LICENSE_FILE = (
    "LICENCE.txt"  # NOLINT(american-spelling): the file's name in the repository.
)
ADVICE = (
    "start the file with the repository's BSD-3 license block as a comment: `Copyright (c) <year>, <holder>. All rights "
    "reserved.`, the conditions and the disclaimer (copy it from a neighboring file)"
)
_MARKERS = re.compile(r"^[\s/*#]*")
_TRAILING_MARKERS = re.compile(r"[\s*/]*$")
_GENERATED = re.compile(r"^\W*Generated by ")


def comment_lines(comment: str) -> list[str]:
    """The lines of a comment without their markers: `/*`, `*/`, `//`, `#`, a leading `*` and bullets."""
    lines = []
    for line in comment.splitlines():
        stripped = _MARKERS.sub("", line)
        stripped = (
            _TRAILING_MARKERS.sub("", stripped)
            if line.rstrip().endswith("*/")
            else stripped.rstrip()
        )
        lines.append(stripped)
    return lines


def problems(lines: list[str]) -> list[str]:
    """What the license block, given as its comment_lines(), lacks; empty when it is complete.

    Args:
      lines: The lines of the file's first comment, without their comment markers.

    Returns:
      One message per problem: no holder line, a holder line without its holder, and each missing part.
    """
    holder_lines = [
        line.strip() for line in lines if line.strip().startswith("Copyright")
    ]
    if not holder_lines:
        return [f"no license header: {ADVICE}"]
    found = []
    for line in holder_lines:
        if not HOLDER_LINE.match(line):
            found.append(
                f"the holder line `{line}` is not `Copyright (c) <year>, <holder>. All rights reserved.`: name the "
                "holder (`git log` says who wrote the file)"
            )
    text = " ".join(" ".join(lines).split())
    missing = [] if PREAMBLE in text else ["the preamble"]
    missing += [name for name, condition in CONDITIONS if condition not in text]
    if DISCLAIMER not in text:
        missing.append("the disclaimer")
    if missing:
        found.append(
            f"the license block lacks {', '.join(missing)} of the BSD 3-Clause License: {ADVICE}"
        )
    return found


def leading_cpp_comment(source: str) -> tuple[str, int, int]:
    """The comments that start a C++ file, before its first code or preprocessor token.

    Args:
      source: The file.

    Returns:
      The comments' text, the line they start on, and the line of the first token after them (where the file's code
      starts).
    """
    comments: list[str] = []
    start = 1
    end = len(source.splitlines()) or 1
    for token in cpp_source.tokenize(source, keep_preprocessor=True):
        if token.kind != cpp_source.COMMENT:
            end = token.line
            break
        if not comments:
            start = token.line
        comments.append(token.text)
    return "\n".join(comments), start, end


def finding_lines(lines: list[str], start: int, end: int) -> list[tuple[int, str]]:
    """problems() of a block whose comment_lines() are `lines`, each with its line: a holder line's own, else `end`.

    Args:
      lines: The block's lines without their markers, the first on line `start`.
      start: The line the block starts on.
      end: The line the file's code starts on, after the block.

    Returns:
      (line, message) for each problem.
    """
    found = []
    for message in problems(lines):
        line = end
        for offset, text in enumerate(lines):
            if text.strip() and f"`{text.strip()}`" in message:
                line = start + offset
                break
        found.append((line, message))
    return found


def check_source(source: str, path: str = "<source>") -> list[check_types.Finding]:
    """The findings of `license-header` in the C++ `source` of the file at `path`."""
    if not source.strip():
        return []
    comment, start, end = leading_cpp_comment(source)
    lines = comment_lines(comment)
    first = next((text for text in lines if text.strip()), "")
    if _GENERATED.match(first):
        return []
    return [
        check_types.Finding(path, line, 1, NAME, f"{message} (AGENTS.md, decision D5).")
        for line, message in finding_lines(lines, start, end)
    ]


CHECKS = [
    check_types.Check(
        name=NAME,
        languages=frozenset({check_types.Language.CPP}),
        scope=lint_files.Scope.FIRST_PARTY,
        check_source=check_source,
        description="every C++ file starts with the repository's BSD-3 license block, with a named holder (AGENTS.md; D5).",
        hint="Copy the block of a neighboring file. A holder line names its holder (`git log`); an existing holder is "
        "kept.",
    )
]
