centroidalModelType: 0  # 0: FullCentroidalDynamics, 1: Single Rigid Body Dynamics

interface:
  verbose: true  # show the loaded parameters
  useAnalyticalGradientsDynamics: false
  useAnalyticalGradientsConstraints: false

model_settings:
  robotName: atlas

  foot_constraint:
    positionErrorGain_z: 5.0
    orientationErrorGain: 3.0
    linearVelocityErrorGain_z: 1.0
    linearVelocityErrorGain_xy: 1.0
    angularVelocityErrorGain: 0.2
    linearAccelerationErrorGain_z: 0.0
    linearAccelerationErrorGain_xy: 0.0
    angularAccelerationErrorGain: 0.0

  phaseTransitionStanceTime: 0.0

  verboseCppAd: true
  recompileLibrariesCppAd: false
  modelFolderCppAd: build/wb_mpc_cppad_autocode_gen

  # Exclude these joints from MPC model
  fixedJointNames:
    - l_arm_wry
    - l_arm_wrx
    - r_arm_wry
    - r_arm_wrx

  # Pinocchio Frame names for the contact frames
  contactNames6DoF:
    - foot_l_contact
    - foot_r_contact

  # The Parent frames on which the contact frames are added.
  contactParentJointNames:
    - l_leg_akx
    - r_leg_akx

  # ; Used for arm swing reference
  armJointNames:
    left_shoulder_y: l_arm_shx
    right_shoulder_y: r_arm_shx
    left_elbow_y: l_arm_elx
    right_elbow_y: r_arm_elx

swing_trajectory_config:
  liftOffVelocity: 0.05
  touchDownVelocity: -0.05
  swingHeight: 0.08
  touchDownHeightOffset: 0.0
  swingTimeScale: 0.4
  impactProximityFactorLiftOffVelocity: -0.15
  impactProximityFactorTouchDownVelocity: 0.3
  impactProximityFactorMidPointValue: 0.0

# multiple_shooting settings
multiple_shooting:
  nThreads: 4
  dt: 0.02
  sqpIteration: 1
  deltaTol: 1e-4
  g_max: 1e-2
  g_min: 1e-6
  inequalityConstraintMu: 0.1
  inequalityConstraintDelta: 5.0
  projectStateInputEqualityConstraints: true
  printSolverStatistics: true
  printSolverStatus: false
  printLinesearch: false
  useFeedbackPolicy: false
  integratorType: RK4
  threadPriority: 50

# Rollout settings
rollout:
  AbsTolODE: 5e-5
  RelTolODE: 5e-3
  timeStep: 0.015
  integratorType: ODE45
  maxNumStepsPerSecond: 10000
  checkNumericalStability: false

mpc:
  timeHorizon: 1.2  # [s]
  solutionTimeWindow: -1  # maximum [s]
  coldStart: false

  debugPrint: false

  mpcDesiredFrequency: 80  # [Hz]
  mrtDesiredFrequency: 100  # [Hz]

initialState:
  # ; Normalized Centroidal Momentum: [linear, angular] ;;
  "(0,0)": 0.0  # h_com_x / robotMass
  "(1,0)": 0.0  # h_com_y / robotMass
  "(2,0)": 0.0  # h_com_z / robotMass
  "(3,0)": 0.0  # L_x / robotMass
  "(4,0)": 0.0  # L_y / robotMass
  "(5,0)": 0.0  # L_z / robotMass

  # ; Base Pose: [position, orientation] ;;
  "(6,0)": 0.0  # p_base_x
  "(7,0)": 0.0  # p_base_y
  "(8,0)": 0.895  # p_base_z
  "(9,0)": 0.0  # theta_base_z
  "(10,0)": 0.0  # theta_base_y
  "(11,0)": 0.0  # theta_base_x

  # ; Joint Positions: ;;
  "(12,0)": 0.0  # back_bkz
  "(13,0)": 0.0  # back_bky
  "(14,0)": 0.0  # back_bkx
  "(15,0)": 0.3  # l_arm_shz
  "(16,0)": -1.2  # l_arm_shx
  "(17,0)": 2.2  # l_arm_ely
  "(18,0)": 0.55  # l_arm_elx
  "(19,0)": 0.0  # neck_ry
  "(20,0)": -0.3  # r_arm_shz
  "(21,0)": 1.2  # r_arm_shx
  "(22,0)": 2.2  # r_arm_ely
  "(23,0)": -0.55  # r_arm_elx
  "(24,0)": 0.0  # l_leg_hpz
  "(25,0)": 0.0  # l_leg_hpx
  "(26,0)": -0.42  # l_leg_hpy
  "(27,0)": 0.84  # l_leg_kny
  "(28,0)": -0.42  # l_leg_aky
  "(29,0)": 0.0  # l_leg_akx
  "(30,0)": 0.0  # r_leg_hpz
  "(31,0)": 0.0  # r_leg_hpx
  "(32,0)": -0.42  # r_leg_hpy
  "(33,0)": 0.84  # r_leg_kny
  "(34,0)": -0.42  # r_leg_aky
  "(35,0)": 0.0  # r_leg_akx

# standard state weight matrix
Q:
  scaling: 1e+0

  # ; Normalized Centroidal Momentum: [linear, angular] ;;
  "(0,0)": 5.0  # h_com_x / robotMass
  "(1,1)": 5.0  # h_com_y / robotMass
  "(2,2)": 15.0  # h_com_z / robotMass
  "(3,3)": 5.0  # L_x / robotMass
  "(4,4)": 5.0  # L_y / robotMass
  "(5,5)": 2.0  # L_z / robotMass

  # ; Base Pose: [position, orientation] ;;
  "(6,6)": 1.0  # p_base_x
  "(7,7)": 1.0  # p_base_y
  "(8,8)": 40.0  # p_base_z
  # euler angles for base to world rotation
  "(9,9)": 10.0  # theta_base_z
  "(10,10)": 10.0  # theta_base_y
  "(11,11)": 10.0  # theta_base_x

  # ; Joint Positions ;;
  "(12,12)": 0.5  # back_bkz
  "(13,13)": 0.5  # back_bky
  "(14,14)": 0.5  # back_bkx
  "(15,15)": 0.1  # l_arm_shz
  "(16,16)": 0.1  # l_arm_shx
  "(17,17)": 0.1  # l_arm_ely
  "(18,18)": 0.1  # l_arm_elx
  "(19,19)": 0.2  # neck_ry
  "(20,20)": 0.1  # r_arm_shz
  "(21,21)": 0.1  # r_arm_shx
  "(22,22)": 0.1  # r_arm_ely
  "(23,23)": 0.1  # r_arm_elx
  "(24,24)": 2.0  # l_leg_hpz
  "(25,25)": 2.0  # l_leg_hpx
  "(26,26)": 2.0  # l_leg_hpy
  "(27,27)": 0.4  # l_leg_kny
  "(28,28)": 4.0  # l_leg_aky
  "(29,29)": 4.0  # l_leg_akx
  "(30,30)": 2.0  # r_leg_hpz
  "(31,31)": 2.0  # r_leg_hpx
  "(32,32)": 2.0  # r_leg_hpy
  "(33,33)": 0.4  # r_leg_kny
  "(34,34)": 4.0  # r_leg_aky
  "(35,35)": 4.0  # r_leg_akx

# control weight matrix
R:
  scaling: 1e-3

  # ; Feet Contact Forces: [LF, RF, LH, RH] ;;
  "(0,0)": 0.01  # left_force_x
  "(1,1)": 0.01  # left_force_y
  "(2,2)": 0.01  # left_force_z
  "(3,3)": 0.1  # left_moment_x
  "(4,4)": 0.1  # left_moment_y
  "(5,5)": 0.1  # left_moment_z
  "(6,6)": 0.01  # right_force_x
  "(7,7)": 0.01  # right_force_y
  "(8,8)": 0.01  # right_force_z
  "(9,9)": 0.1  # right_moment_x
  "(10,10)": 0.1  # right_moment_y
  "(11,11)": 0.1  # right_moment_z

  # ; Joint Velocities ;;
  "(12,12)": 20.0  # back_bkz
  "(13,13)": 20.0  # back_bky
  "(14,14)": 20.0  # back_bkx
  "(15,15)": 20.0  # l_arm_shz
  "(16,16)": 20.0  # l_arm_shx
  "(17,17)": 20.0  # l_arm_ely
  "(18,18)": 20.0  # l_arm_elx
  "(19,19)": 20.0  # neck_ry
  "(20,20)": 20.0  # r_arm_shz
  "(21,21)": 20.0  # r_arm_shx
  "(22,22)": 20.0  # r_arm_ely
  "(23,23)": 20.0  # r_arm_elx
  "(24,24)": 20.0  # l_leg_hpz
  "(25,25)": 20.0  # l_leg_hpx
  "(26,26)": 20.0  # l_leg_hpy
  "(27,27)": 20.0  # l_leg_kny
  "(28,28)": 20.0  # l_leg_aky
  "(29,29)": 20.0  # l_leg_akx
  "(30,30)": 20.0  # r_leg_hpz
  "(31,31)": 20.0  # r_leg_hpx
  "(32,32)": 20.0  # r_leg_hpy
  "(33,33)": 20.0  # r_leg_kny
  "(34,34)": 20.0  # r_leg_aky
  "(35,35)": 20.0  # r_leg_akx


terminalCostScaling: 4.0
Q_final:
  scaling: 1e+0

  # ; Normalized Centroidal Momentum: [linear, angular] ;;
  "(0,0)": 5.0  # h_com_x / robotMass
  "(1,1)": 5.0  # h_com_y / robotMass
  "(2,2)": 15.0  # h_com_z / robotMass
  "(3,3)": 5.0  # L_x / robotMass
  "(4,4)": 5.0  # L_y / robotMass
  "(5,5)": 2.0  # L_z / robotMass

  # ; Base Pose: [position, orientation] ;;
  "(6,6)": 1.0  # p_base_x
  "(7,7)": 1.0  # p_base_y
  "(8,8)": 40.0  # p_base_z
  # euler angles for base to world rotation
  "(9,9)": 10.0  # theta_base_z
  "(10,10)": 10.0  # theta_base_y
  "(11,11)": 10.0  # theta_base_x

  # ; Joint Positions ;;
  "(12,12)": 0.5  # back_bkz
  "(13,13)": 0.5  # back_bky
  "(14,14)": 0.5  # back_bkx
  "(15,15)": 0.1  # l_arm_shz
  "(16,16)": 0.1  # l_arm_shx
  "(17,17)": 0.1  # l_arm_ely
  "(18,18)": 0.1  # l_arm_elx
  "(19,19)": 0.2  # neck_ry
  "(20,20)": 0.1  # r_arm_shz
  "(21,21)": 0.1  # r_arm_shx
  "(22,22)": 0.1  # r_arm_ely
  "(23,23)": 0.1  # r_arm_elx
  "(24,24)": 2.0  # l_leg_hpz
  "(25,25)": 2.0  # l_leg_hpx
  "(26,26)": 2.0  # l_leg_hpy
  "(27,27)": 0.4  # l_leg_kny
  "(28,28)": 4.0  # l_leg_aky
  "(29,29)": 4.0  # l_leg_akx
  "(30,30)": 2.0  # r_leg_hpz
  "(31,31)": 2.0  # r_leg_hpx
  "(32,32)": 2.0  # r_leg_hpy
  "(33,33)": 0.4  # r_leg_kny
  "(34,34)": 4.0  # r_leg_aky
  "(35,35)": 4.0  # r_leg_akx

icp_cost_weights:
  icpErrorWeight: 500.0

task_space_foot_cost_weights:
  pos_x: 0.0
  pos_y: 0.0
  pos_z: 0.0
  orientation_x: 1000.0
  orientation_y: 1000.0
  orientation_z: 0.0
  lin_velocity_x: 10.0
  lin_velocity_y: 10.0
  lin_velocity_z: 0.0
  ang_velocity_x: 1.0
  ang_velocity_y: 1.0
  ang_velocity_z: 0.005
  lin_acceleration_x: 0.0
  lin_acceleration_y: 0.0
  lin_acceleration_z: 0.0
  ang_acceleration_x: 0.0
  ang_acceleration_y: 0.0
  ang_acceleration_z: 0.0

task_space_costs:
  torso:
    link_name: utorso
    weights:
      pos_x: 0.0
      pos_y: 0.0
      pos_z: 0.0
      orientation_x: 1.0
      orientation_y: 1.0
      orientation_z: 0.0
      lin_velocity_x: 0.1
      lin_velocity_y: 0.1
      lin_velocity_z: 0.005
      ang_velocity_x: 50.0
      ang_velocity_y: 50.0
      ang_velocity_z: 2.0
      lin_acceleration_x: 0.0
      lin_acceleration_y: 0.0
      lin_acceleration_z: 0.0
      ang_acceleration_x: 0.0
      ang_acceleration_y: 0.0
      ang_acceleration_z: 0.0

left_leg_torque_cost:
  activeJointNames:
    - l_leg_hpz
    - l_leg_hpx
    - l_leg_hpy
    - l_leg_kny
    - l_leg_aky
    - l_leg_akx

  weights:
    scaling: 1e-4

    "(0,0)": 2.0
    "(1,0)": 2.0
    "(2,0)": 1.0
    "(3,0)": 8.0
    "(4,0)": 0.2
    "(5,0)": 0.2

right_leg_torque_cost:
  activeJointNames:
    - r_leg_hpz
    - r_leg_hpx
    - r_leg_hpy
    - r_leg_kny
    - r_leg_aky
    - r_leg_akx

  weights:
    scaling: 1e-4

    "(0,0)": 2.0
    "(1,0)": 2.0
    "(2,0)": 1.0
    "(3,0)": 8.0
    "(4,0)": 0.2
    "(5,0)": 0.2

contacts:
  contact_frame_translation:
    # ; Translation vector from parent joint to contact frame (bottom of foot just below ankle) ;;
    x: 0.0
    y: 0.0
    z: -0.076
  contact_rectangle:
    # ; length specified in contact frame ;;
    x_max: 0.17
    x_min: -0.09
    y_max: 0.07
    y_min: -0.07

  contactWrenchConeSoftConstraint:
    frictionCoefficient: 0.7
    torsionalFrictionCoefficient: 0.05
    minNormalForce: 5.0
    gripperForce: 0.0
    numBasisVectors: 8
    # relaxed log barrier parameters
    mu: 0.2
    delta: 5.0

jointLimits:
  # relaxed log barrier parameters
  mu: 1200.0
  delta: 0.1

collision_constraint:
  foot:
    leftAnkleFrame: l_leg_akx
    rightAnkleFrame: r_leg_akx

    footCollisionSphereRadius: 0.05
  knee:
    leftKneeFrame: l_leg_kny
    rightKneeFrame: r_leg_kny

    kneeCollisionSphereRadius: 0.07
  # relaxed log barrier parameters
  mu: 15000
  delta: 0.04
