ARG ROS_DISTRO=jazzy
ARG BASE_IMAGE=ros:${ROS_DISTRO}-ros-base
FROM ${BASE_IMAGE} AS base

ARG CPP_VERSION=20
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG WB_HUMANOID_MPC_DIR="/wb_humanoid_mpc_ws"
ARG PYTHON_VERSION=3.12
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=${ROS_DISTRO}

# Install clang-format (for linting).
ARG CLANG_VERSION=18

# Install LLVM GPG key and add repository.
RUN UBUNTU_DISTRO=$(lsb_release -cs) && \
    apt-get update && \
    apt-get install -y wget gnupg && \
    wget https://apt.llvm.org/llvm-snapshot.gpg.key && \
    apt-key add llvm-snapshot.gpg.key && \
    rm llvm-snapshot.gpg.key && \
    echo "deb http://apt.llvm.org/${UBUNTU_DISTRO}/ llvm-toolchain-${UBUNTU_DISTRO}-${CLANG_VERSION} main" | tee /etc/apt/sources.list.d/llvm.list

# Update package list and install clang-format.
RUN apt-get update && \
    apt-get install -y clang-format-${CLANG_VERSION} && \
    ln -s /usr/bin/clang-format-${CLANG_VERSION} /usr/bin/clang-format

# Update package list and install clang-tidy.
RUN apt-get update && \
    apt-get install -y clang-tidy-${CLANG_VERSION} && \
    ln -s /usr/bin/clang-tidy-${CLANG_VERSION} /usr/bin/clang-tidy && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install system dependencies, ROS, Python, and development tools in a single step
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl gnupg2 lsb-release software-properties-common \
    locales \
    git \
    x11-apps \
    mesa-utils \
    gettext-base \
    && rm -rf /var/lib/apt/lists/*

# Install Abseil
RUN git clone -b 20240722.0 https://github.com/abseil/abseil-cpp.git && \
    cd abseil-cpp && \
    mkdir -p build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . --target install && \
    ldconfig

# Copy dependencies file
COPY dependencies.txt /tmp/dependencies.txt

# Set up environment variables
ENV CMAKE_PREFIX_PATH="/opt/ros/${ROS_DISTRO}:${CMAKE_PREFIX_PATH}"
ENV DISPLAY=${DISPLAY:-:0} QT_X11_NO_MITSHM=1

# Install dependencies from dependencies.txt
RUN apt-get update && \
    envsubst < /tmp/dependencies.txt | xargs apt-get install -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Set default shell to bash
SHELL ["/bin/bash", "-c"]

# Set up user and workspace
WORKDIR ${WB_HUMANOID_MPC_DIR}
RUN mkdir -p ${WB_HUMANOID_MPC_DIR}/src/wb_humanoid_mpc

# Ensure correct UID/GID
RUN if ! getent group $GROUP_ID > /dev/null; then groupadd --gid $GROUP_ID devgroup; fi && \
    if ! getent passwd $USER_ID > /dev/null; then useradd --uid $USER_ID --gid $GROUP_ID --create-home devuser; fi && \
    chown -R $USER_ID:$GROUP_ID .

# Copy the Makefile and other necessary files
COPY . ${WB_HUMANOID_MPC_DIR}/src/wb_humanoid_mpc
