version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
      args:
        WB_HUMANOID_MPC_DIR: "/wb_humanoid_mpc_ws"
        PYTHON_VERSION: "3.12"
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
        GIT_USER_NAME: "${GIT_USER_NAME}"
        GIT_USER_EMAIL: "${GIT_USER_EMAIL}"

    # platform selectable via DOCKER_PLATFORM on host; default uses amd64 (Rosetta on Apple Silicon)
    platform: ${DOCKER_PLATFORM:-linux/amd64}

    user: "${CONTAINER_USER:-ubuntu}"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: sleep infinity

    volumes:
      - ../../..:/wb_humanoid_mpc_ws:delegated
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR:-/tmp/xdg_runtime_dir}:${XDG_RUNTIME_DIR:-/tmp/xdg_runtime_dir}
      - ${HOME}/.gitconfig:/tmp/host.gitconfig:cached,ro
      - ${HOME}/.ssh:/tmp/host_ssh:cached,z

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      COLCON_HOME: /wb_humanoid_mpc_ws
      COLCON_DEFAULTS_FILE: /wb_humanoid_mpc_ws/src/wb_humanoid_mpc/colcon.defaults.yaml