load("//bazel:robot_files.bzl", "ROBOT_FILE_EXCLUDES")
# drc_atlas_description - URDF, meshes, launch, rviz data files for DRC Atlas

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "drc_atlas_description",
    srcs = glob([
        "urdf/**",
        "meshes/**",
        "launch/**",
        "rviz/**",
        "materials/**",
    ], exclude = ROBOT_FILE_EXCLUDES, allow_empty = True),
)
